# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  pipelines:
    - pipeline: buildContosoAir
      source: bellstar.ContosoAir
      trigger:
        branches:
          include:
            - master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '7ecfa090-f719-4e00-a538-61275ee5cdf0'
    definition: '82'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'CSR-CUSPOC-MST-himiyaza(f1e5a674-6515-42f9-b54a-4d6f12983ea4)'
    subscriptionId: 'f1e5a674-6515-42f9-b54a-4d6f12983ea4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'tailspin-rg'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
    csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'CSR-CUSPOC-MST-himiyaza(f1e5a674-6515-42f9-b54a-4d6f12983ea4)'
    appType: 'webApp'
    WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'